### ISSUE TITLE
Plugin not working after latest PAW update

### ISSUE THREAD

**Issue by hnnnglmbrg** [xelaris/paw-wsse-dynamic-value#2]
When PAW gets updated to the latest version, this plugin is not working anymore.

**Comment by albohlabs** [comment]
![feature](http://cdn.meme.am/instances/57398326.jpg)

**Comment by hnnnglmbrg** [comment]
Still buggy...

**Comment by albohlabs** [comment]
![broken](http://cf.chucklesnetwork.com/items/3/4/9/2/2/original/checked-in-bad-code-build-already-broken-nobody-noticed.jpg)

**Comment by albohlabs** [comment]
Only two participants … :angry:

**Comment by xelaris** [comment]
Have a look at the brand-new release https://github.com/xelaris/paw-wsse-dynamic-value/releases/download/1.0.0/WsseDynamicValue.zip

**Comment by albohlabs** [comment]
Works like a charm.

**Comment by hnnnglmbrg** [comment]
Fixed.
