### ISSUE TITLE
Usage documentation

### ISSUE THREAD

**Issue by iovis** [xelaris/paw-wsse-dynamic-value#4]
I'm failing to use the extension :(
I'm sure it's my fault but having a nice documentation would help me a lot!

**Comment by xelaris** [comment]
Hey! Thanks for your feedback. Please have a look at https://paw.cloud/docs/dynamic-values/introduction. Dynamic values are a generic concept of paw, so this doc may help you out. If it still don't work, please let me know.

**Comment by iovis** [comment]
There you go, I didn't know I could use them on the body nor the `{` shortcut for autocompletion! I knew I was missing something.
